from .universidad_mapping import UniversidadMapping
from .area_mapping import AreaMapping
from .tipodedicacion_mapping import TipoDedicacionMapping
from .categoriacargo_mapping import CategoriaCargoMapping
from .grupo_mapping import GrupoMapping
from .grado_mapping import GradoMapping
from .departamento_mapping import DepartamentoMapping
from .tipoespecialidad_mapping import TipoEspecialidadMapping
from .plan_mapping import PlanMapping
from .cargo_mapping import CargoMapping
from .alumno_mapping import AlumnoMapping
from .nota_mapping import NotaMapping
from .materia_mapping import MateriaMapping
from .autoridad_mapping import Autoridad
from .documento_mapping import Documento
from .especialidad_mapping import Especialidad
from .facultad_mapping import Facultad
from .orientacion_mapping import Orientacion
