from .tipo_especialidad_mapping import TipoEspecialidadMapping
from .nota_mapping import NotaMapping
from .materia_mapping import MateriaMapping
from .plan_mapping import PlanMapping
from .categoriacargo_mapping import CategoriaCargoMapping
from .tipodedicacion_mapping import TipoDedicacionMapping
from .especialidad_mapping import EspecialidadMappingMapping
from .documento_mapping import DocumentoMapper
from .alumno_mapping import AlumnoMapper
from .grado_mapping import GradoMapping
from .grupo_mapping import GrupoMapping
from .cargo_mapping import CargoMapping
from .orientacion_mapping import OrientacionMapping
from .area_mapping import AreaMapping
from .departamento_mapping import DepartamentoMapping
from .facultad_mapping import FacultadMapper
from .autoridad_mapping import AutoridadMapping
from .universidad_mapping import UniversidadMapping
